/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DialogClose: typeof import('reka-ui')['DialogClose']
    DialogContent: typeof import('reka-ui')['DialogContent']
    DialogDescription: typeof import('reka-ui')['DialogDescription']
    DialogOverlay: typeof import('reka-ui')['DialogOverlay']
    DialogPortal: typeof import('reka-ui')['DialogPortal']
    DialogRoot: typeof import('reka-ui')['DialogRoot']
    DialogTitle: typeof import('reka-ui')['DialogTitle']
    ThreeCanvas: typeof import('./components/ThreeCanvas.vue')['default']
    YButton: typeof import('./components/button/y-button.vue')['default']
    YDialog: typeof import('./components/dialog/y-dialog.vue')['default']
    YHvAbsoluteCenter: typeof import('./components/layout/center/y-hv-absolute-center.vue')['default']
    YHvCenter: typeof import('./components/layout/center/y-hvCenter.vue')['default']
    YProgress: typeof import('./components/progress/y-progress.vue')['default']
  }
}

// For TSX support
declare global {
  const DialogClose: typeof import('reka-ui')['DialogClose']
  const DialogContent: typeof import('reka-ui')['DialogContent']
  const DialogDescription: typeof import('reka-ui')['DialogDescription']
  const DialogOverlay: typeof import('reka-ui')['DialogOverlay']
  const DialogPortal: typeof import('reka-ui')['DialogPortal']
  const DialogRoot: typeof import('reka-ui')['DialogRoot']
  const DialogTitle: typeof import('reka-ui')['DialogTitle']
  const ThreeCanvas: typeof import('./components/ThreeCanvas.vue')['default']
  const YButton: typeof import('./components/button/y-button.vue')['default']
  const YDialog: typeof import('./components/dialog/y-dialog.vue')['default']
  const YHvAbsoluteCenter: typeof import('./components/layout/center/y-hv-absolute-center.vue')['default']
  const YHvCenter: typeof import('./components/layout/center/y-hvCenter.vue')['default']
  const YProgress: typeof import('./components/progress/y-progress.vue')['default']
}